### ISSUE TITLE
insufficient memory error

### ISSUE THREAD

**Issue by YajieW99** [kevinliang888/IVR-QA-baselines#2]
Hello! When I run the Heuristic eval_interactive.py, an OOM error will happen during the process. I use 4*A100 32GB GPUs, what GPU does you use? Or is there something wrong with the code? Looking forward to your help.
![Snipaste_2024-01-08_16-03-05](https://github.com/kevinliang888/IVR-QA-baselines/assets/44310850/032e6efc-dfd1-4dd0-b990-4bc174a2d5c5)

**Comment by kevinliang888** [comment]
I used an RTX3090 with 24GB for the Heuristic approach, and an A6000 with 48GB for the Auto-text or Auto-text-vid approaches. Based on this experience, using an NVIDIA A100 should pose no issues for the Heuristic approach, given its better memory.

I recommend using only one GPU for inference first. This stems from the potential for unforeseen complications that might arise with a multi-GPU setup. 

Hope this helps!

**Comment by YajieW99** [comment]
> I used an RTX3090 with 24GB for the Heuristic approach, and an A6000 with 48GB for the Auto-text or Auto-text-vid approaches. Based on this experience, using an NVIDIA A100 should pose no issues for the Heuristic approach, given its better memory.
> 
> I recommend using only one GPU for inference first. This stems from the potential for unforeseen complications that might arise with a multi-GPU setup.
> 
> Hope this helps!

Thanks for help, I'll have a try!

**Comment by SunQuantao0** [comment]
When pytorch runs the sleep staging program, the video memory occupies a particularly large sleep-edf20 dataset and the occupation reaches 20G, how to solve this, ask for help
